// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOAE-uERhMc0CFp3yMmKBZCYaOKHHa_FM',
    appId: '1:15352402606:web:3259b41bbfdc291e5dd33f',
    messagingSenderId: '15352402606',
    projectId: 'colorlist-lyx',
    authDomain: 'colorlist-lyx.firebaseapp.com',
    storageBucket: 'colorlist-lyx.firebasestorage.app',
    measurementId: 'G-FBJFNPM8RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpQCOJ39rJWjQl-OL0ODA7nkF8wS_zSGU',
    appId: '1:15352402606:android:291c0618e1c721cb5dd33f',
    messagingSenderId: '15352402606',
    projectId: 'colorlist-lyx',
    storageBucket: 'colorlist-lyx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7I9zUQGuMK9OysZxPcZdscon-OCGsXFA',
    appId: '1:15352402606:ios:cd06405eba22b6315dd33f',
    messagingSenderId: '15352402606',
    projectId: 'colorlist-lyx',
    storageBucket: 'colorlist-lyx.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7I9zUQGuMK9OysZxPcZdscon-OCGsXFA',
    appId: '1:15352402606:ios:cd06405eba22b6315dd33f',
    messagingSenderId: '15352402606',
    projectId: 'colorlist-lyx',
    storageBucket: 'colorlist-lyx.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOAE-uERhMc0CFp3yMmKBZCYaOKHHa_FM',
    appId: '1:15352402606:web:5f42730689dadca25dd33f',
    messagingSenderId: '15352402606',
    projectId: 'colorlist-lyx',
    authDomain: 'colorlist-lyx.firebaseapp.com',
    storageBucket: 'colorlist-lyx.firebasestorage.app',
    measurementId: 'G-D9LCHQQ4FN',
  );

}